# AUTO-GENERATED by branchkit-cli dev init — regenerate with: branchkit-gen --plugin .
from typing import NotRequired, TypedDict

# GreetParams is the params shape for action "helloworld.greet (Greet)".
GreetParams = TypedDict("GreetParams", {
    "name": NotRequired[str],
})
