# AUTO-GENERATED by emit-sdk — do not edit.
# Source: plugin.json `action_types`. Run: just gen-plugins

from typing import NotRequired, TypedDict

# Params shape for action "helloworld.greet (Greet)".
GreetParams = TypedDict("GreetParams", {
    "name": NotRequired[str],
})

def handle_greet(plugin, fn=None):
    """Register a handler for action "helloworld.greet (Greet)" — `fn(req)` where
    req["params"] is GreetParams-shaped."""
    return plugin.handle_action("helloworld.greet", fn)
