# Code generated by branchkit-gen from plugin.json `action_types`. DO NOT EDIT.
# Regenerate from the plugin directory: branchkit-gen --plugin .

from typing import NotRequired, TypedDict

# Params shape for action "helloworld.greet (Greet)".
GreetParams = TypedDict("GreetParams", {
    "name": NotRequired[str],
})

def handle_greet(plugin, fn=None):
    """Register a handler for action "helloworld.greet (Greet)" — `fn(req)` where
    req["params"] is GreetParams-shaped."""
    return plugin.handle_action("helloworld.greet", fn)
